### ISSUE TITLE
Peer review of data management plan

### ISSUE THREAD

**Issue by nbir012** [UOA-MEDSCI-736/dvasques83-medsci736#3]
Hi Demi,
The DMP looks good and overall you have done a thorough job, top-notch! A few minor points:

For 'Funding ID' and 'Research Office ID' on page 2, instead of N/A put whay you don't have it (in my case I put that we require the info from Fabiana).

For 'Ethics Requirements' and 'Are there other privacy and/or security requirements?' on page 2, state why you don't require it (e.g. not using data that has any ethical issues and advised by supervisor that this is the case). That way people will know that you have considered it and found that it is not applicable. You can then just place 'N/A' for the 'How will you manage any ethical issues?'.

For 'Storage Locations' on page 3, it may be worth considering storing the data on the university's server as well as this has long term storage plans, regular backups etc. More info on this can be found on the university's website.

For 'What documentation and metadata will accompany the data to support its discovery, (re)use and increase impact?' on page 3, explaining what format the metadata will be in and what any documentation will look like would be useful so some poor post-grad slave in 2026 who picks up the DMP to review something knows exactly what to look for.

Good luck and great project!

Neil

**Comment by dvasques83** [comment]
Hi Neil, sorry it took me so long to work on your feedback.
Thank you very much for that. It seems a little more informative now.

Cheers,

Demi.

**Comment by nbir012** [comment]
Hi Demi, it looks good - I will close this issue
