### ISSUE TITLE
DMP Peer Review

### ISSUE THREAD

**Issue by BibianaLee** [UOA-MEDSCI-736/dvasques83-medsci736#5]
Hi Demi, 

Your DMP is looking good and has direction but it's looking a bit sparse here and there. 
Judging from the feedback I've gotten on my own DMP I think it's important to be completely clear on 
- why and how you're going to achieve or do anything during and after your project. 
- Whose google drive, github repository etc. are you going to utilize for the longevity of your data? 
- What will your metadata contain and why is this relevant to your project? 
- Why are the related policies relevant to your project? 

Overall, your DMP is good and I think it'll look better once it's finalized and finished :) 

I hope this helped. 
Kind Regards, 

Bibiana

**Comment by dvasques83** [comment]
Hi Bibiana, thanks for your feedback.

It seems it has a little bit more information now.
Let me know if you are happy with the changes I've made.

Cheers,
Demi

**Comment by BibianaLee** [comment]
Hi Demi, 

Looks better :) I'll close the issue now 
Good luck for the rest of the year !
